[target.'cfg(all(target_os = "windows", target_env="msvc"))']
rustflags = [
    # Statically compile the windows C runtime. This increases size but is good for portability
    #"-C", "target-feature=+crt-static",
    
    # Link Args
    # /EMITPHOPHASEINFO     Removes the .debug segment
    # /DEBUG:NONE           Do not include PDB path in binary or generate PDB
    # /MERGE                Combine segments with similar permissions
    # /MANIFEST:NO          Dont generate any manifest file
    "-C", "link-args=/EMITPOGOPHASEINFO /DEBUG:NONE /MERGE:.pdata=.text /MERGE:.rdata=.text /MANIFEST:NO"
]

[profile.release]
debug = false
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[unstable]
# Build the panic_abort crate and all of std using our crate's profile settings
# In most cases, this means that panics will generate either an abort() of an invalid instruction exception
build-std = ["panic_abort", "std"]

# Dont run anything else on panic.
# This removes any pretty printing of error messages with their location (file paths)
build-std-features = ["panic_immediate_abort"]