[target.'cfg(all(target_family = "windows", target_env="msvc"))']
rustflags = [
    # Statically compile the windows C runtime. This increases size but is good for portability
    #"-C", "target-feature=+crt-static",
    
    # Link Args
    # /EMITPHOPHASEINFO     Removes the .debug segment
    # /MERGE                Combine segments with similar permissions
    "-C", "link-args=/EMITPOGOPHASEINFO /MERGE:.pdata=.text /MERGE:.rdata=.text"
]

[profile.release]
debug = false
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = "symbols"

[unstable]
# Build the panic_abort crate and all of std using our crate's profile settings
# Depending on the crate profile `panic` setting, either panic_abort or panic_unwind will be linked in std
build-std = ["panic_abort", "std"]

# Dont run anything else on panic.
# This removes any pretty printing of error messages with their location (file paths)
# This can be provided through the command to allow debug builds to have error messages on panic
# build-std-features = ["panic_immediate_abort"]